version: '3.7'

services:
  war_game:
    image: 725311/war_game:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#    command: gunicorn --bind 0.0.0.0:8000 run:app
    ports:
      - 80:5000
    restart: always
    depends_on:
      -   nginx

  nginx:
    image: nginx:1.19.3
#    ports:
#      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

#version: "3.7"
#services:
#  war_game:
#    image: 725311/war_game:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#    ports:
#      - "80:5000"
#    restart: always
#    depends_on:
#      - db
#  db:
#    image: postgres
#    environment:
#      POSTGRES_USER: $DB_USER
#      POSTGRES_PASSWORD: $DB_PASSWORD
#      POSTGRES_DB: $DB_NAME
