version: '3.7'

services:

  war_game:
    image: 725311/code
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
#    build: ../..
#    command: gunicorn --bind 0.0.0.0:8000 run:app
    restart: always
    depends_on:
      -   db

  db:
    image: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
#      -   nginx

#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - 5000:80
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    restart: always


#version: "3.7"
#services:
#  war_game:
#    image: 725311/war_game:code
#    build: .
#    ports:
#      - "80:5000"
#    restart: always
#    depends_on:
#      - db

